fixed damoang 403 forbidden error.
stateofai/naver-paper pull request #38
Opened 2024-06-11 23:56 UTC by bagng

다모앙 사이트 403 forbidden 오류 처리.

2024-06-12 10:41 UTC, jungx098 requested changes
이 함수내의 다른 requests.get도 HTTP header를 사용하도록 수정이 필요해 보입니다. 결과 값 검증이 필요해 보입니다.

2024-06-12 10:41 UTC, jungx098 commented on naver_paper_damoang.py
> +    response = requests.get(base_url, headers=request_headers)
이것만으로 이 함수가 다시 동작하지 않을 것 같습니다. 이 함수의 다른 부분에도 같은 url에 대하여 requests.get이 사용되고 있습니다. 함수의 결과가 기대한 대로 동작하는지 확인해 보셨나요?

2024-06-12 22:17 UTC, bagng commented on naver_paper_damoang.py
> +    response = requests.get(base_url, headers=request_headers)
제가 oracle cloud에서 결과 값을 출력해보며 확인 했습니다. 다른 사이트는 문제가 없고 다모앙에서만 headers를 주지 않을 경우 403 forbidden 오류가 나서 수정했습니다.

2024-06-12 23:19 UTC, jungx098 commented on naver_paper_damoang.py
> +    response = requests.get(base_url, headers=request_headers)
죄송하지만 현재 패치는 근본 문제점을 수정하지 못하는 것 같습니다; campaign_links (https://github.com/bagng/naver-paper/blob/ff1101adeaedfd904709fae7f026cd2773a759df/naver_paper_damoang.py#L59) 가 empty로 반환됩니다.

아마도 정확한 수정은 HTTP header 수정을 다음의 requests.get에도 적용해야 할 것입니다: https://github.com/bagng/naver-paper/blob/ff1101adeaedfd904709fae7f026cd2773a759df/naver_paper_damoang.py#L41

2024-06-12 23:38 UTC, bagng commented on naver_paper_damoang.py
> +    response = requests.get(base_url, headers=request_headers)
말씀하신 위치도 수정했습니다. 감사합니다.

2024-06-13 01:39 UTC, jungx098 commented
수정이 바르게 된것 같습니다. 감사합니다.

2024-06-14 09:36 UTC, merged

2024-06-14 09:36 UTC, stateofai commented
두분 너무나 감사드립니다!